module Amanuensis
  class StorageService
    class Github

      def latest_release(name, oauth_token)
        client(oauth_token).latest_release(name)
      end

      def create_release(name, oauth_token)
        client(oauth_token).create_release(name, release_name, {
          target_commitish: sha,
          body:             "Release generated by amanuensis based on the commit #{sha}.",
          draft:            false,
          prerelease:       false
        })
      end

      private

      def release_name
        @release_name ||= "release-#{Time.now.strftime('%Y%m%d%H%M%S')}"
      end

      def client(oauth_token)
        @client ||= Octokit::Client.new(access_token: oauth_token, auto_paginate: true)
      end

    end
  end
end
