module Amanuensis
  class CodeManager
    class Github

      def latest_release(configuration)
        client(configuration.oauth_token).latest_release(configuration.repo)
      end

      def create_release(version, configuration)
        client(configuration.oauth_token).create_release(configuration.repo, version, {
          body:       "Release generated by amanuensis.",
          draft:      false,
          prerelease: false
        })
      end

      private

      def client(oauth_token)
        @client ||= Octokit::Client.new(access_token: oauth_token, auto_paginate: true)
      end

    end
  end
end
