module Amanuensis
  class CodeManager
    class Github

      def latest_release(name, oauth_token)
        client(oauth_token).latest_release(name)
      end

      def create_release(name, version, oauth_token)
        client(oauth_token).create_release(name, release_name(version), {
          body:             "Release generated by amanuensis.",
          draft:            false,
          prerelease:       false
        })
      end

      private

      def release_name(version)
        @release_name ||= "#{version}-#{Time.now.strftime('%Y%m%d%H%M%S')}"
      end

      def client(oauth_token)
        @client ||= Octokit::Client.new(access_token: oauth_token, auto_paginate: true)
      end

    end
  end
end
